//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateboarderMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Skateboarder
    {
        public int Id { get; set; }

       [Required(ErrorMessage ="The name of the skateboarder is required")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Home Town")]
        public string HomeTown { get; set; }

        [Display(Name="Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [Required]
        public string Stance { get; set; }

        [Required]
        public string Status { get; set; }

        [Required]
        public string Style { get; set; }

        [Display(Name = "Picture")]
        public string ImageUrl { get; set; }
        [Display(Name = "Video Highlight Url")]
        public string VideoHighlightUrl { get; set; }

        public int Likes { get; set; }

        public int Dislikes { get; set; }

        [Display(Name = "Wheel Sponsor")]
        public string WheelSponsor { get; set; }

        [Display(Name = "Board Sponsor")]
        public string BoardSponsor { get; set; }
    }
}
